### ISSUE TITLE
Korrel8r when deployed using Operator hub doesn't show correlation links

### ISSUE THREAD

**Issue by vprashar2929** [korrel8r/operator#3]
Korrel8r when deployed using default configuration from Operator it doesn't show the correlation link in the logs pannel of console.
default config:
```
kind: Korrel8r
apiVersion: korrel8r.openshift.io/v1alpha1
metadata:
  name: default
  namespace: openshift-operators
```
![Screenshot 2024-02-29 at 11 01 45 PM](https://github.com/korrel8r/operator/assets/115542213/ad1ab16c-7208-44b8-89e1-694f7b43d817)

When Korrel8r instance is created inside `korrel8r` namespace with name as `korrel8r` then it works fine
